export const LABS_PAGE_ROUTE = "/"
export const MAP_PAGE_ROUTE = "/map"
export const LTS_PAGE_ROUTE = "/map/LTS"
export const OSM_PAGE_ROUTE = "/map/OSM"
export const INX_PAGE_ROUTE = "/intersections"
export const PINX_PAGE_ROUTE = "/intersections/protected"